changelog:
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📝 Documentation
      labels:
        - documentation
    - title: 📐 Specifications
      labels:
        - spec
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🧹 Maintenance
      labels:
        - "*"
